name: Build and deploy Website
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

env:
  BUILD_PATH: ${{ github.workspace }}/build
  NODE_VERSION: '16'
  VITE_APP_AZURESEARCH_KEY: ${{ secrets.VITE_APP_AZURESEARCH_KEY }}

jobs:
  build:
    name: Build âš™ï¸ðŸ“¦
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm ci

    - name: Define BASE_PATH environment variable
      run: |
        if [[ "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "BASE_PATH=/" >> "$GITHUB_ENV"
        else
            echo "BASE_PATH=/scoopinstaller-dev.github.io/" >> "$GITHUB_ENV"
        fi

    - name: Build Website
      run: |
        echo "Use BASE_PATH=${{ env.BASE_PATH }}"
        npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: website
        path: ${{ env.BUILD_PATH }}

    - name: Upload stats
      uses: actions/upload-artifact@v3
      with:
        name: stats
        path: ${{ github.workspace }}/build_stats

  deploy:
    if: github.event_name == 'push'
    name: Deploy ðŸš€ðŸŒ
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
          name: website
          path: ${{ env.BUILD_PATH }}

    - name: Deploy website => https://scoop.sh
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./build
        cname: scoop.sh

    - name: Deploy website => https://scoop.sh/scoopinstaller-dev.github.io
      if: github.ref == 'refs/heads/develop'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GHPAGES_DEPLOY_KEY_DEV }}
        external_repository: ScoopInstaller/scoopinstaller-dev.github.io
        publish_branch: master
        publish_dir: ./build
